//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteFlower.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMsg_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMsg_en_US() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EliteFlower.Properties.ResourceMsg-en-US", typeof(ResourceMsg_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you need help?.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure?.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start the process?.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No station has been selected..
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following scanners are missing:.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please connect the missing scanners..
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic balance and selected stations do not match..
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to stop the current process?.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will lose the count and the data you have up to now..
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some parameters have not been selected..
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filename: {0}.
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total of registers: {0}.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable more stages, the file has {0} different products..
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to load the following vases to the selected stage?.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vase {0}: {1},.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendation:.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Station {0} with products.
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to make the change?.
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vase: {0} - Quantity: {1}.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of vases are  {0}.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggest: Use 1 station.
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggest: Use 2 station.
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggest: Use 3 station.
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggest: The machine can not proccess all the orders.
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following IDs are not found in the database..
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the necessary information to continue..
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A manual modification was made, the changed data may not be balanced.
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to upload the generated changes?.
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There were unassigned products found in the file:.
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID: {0} - Quantity: {1].
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It cannot be verified with one or fewer active stations..
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please verify that both files were selected with the same number of stations enabled..
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current configuration can be used..
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current settings cannot be used..
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make the change in.
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a station {0} and.
        /// </summary>
        internal static string T036 {
            get {
                return ResourceManager.GetString("T036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a station {0}..
        /// </summary>
        internal static string T037 {
            get {
                return ResourceManager.GetString("T037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a station {0} with: {1}, {2} and {3}..
        /// </summary>
        internal static string T038 {
            get {
                return ResourceManager.GetString("T038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected stations do not coincide with the current balances..
        /// </summary>
        internal static string T039 {
            get {
                return ResourceManager.GetString("T039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balancing the current file:.
        /// </summary>
        internal static string T040 {
            get {
                return ResourceManager.GetString("T040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balancing the next file:.
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable stations:.
        /// </summary>
        internal static string T042 {
            get {
                return ResourceManager.GetString("T042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select correct stations and / or reload the next file again..
        /// </summary>
        internal static string T043 {
            get {
                return ResourceManager.GetString("T043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a station {0},.
        /// </summary>
        internal static string T044 {
            get {
                return ResourceManager.GetString("T044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enable / disable the stations..
        /// </summary>
        internal static string T045 {
            get {
                return ResourceManager.GetString("T045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to manually select the products that will go by station..
        /// </summary>
        internal static string T046 {
            get {
                return ResourceManager.GetString("T046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enable / disable the bands..
        /// </summary>
        internal static string T047 {
            get {
                return ResourceManager.GetString("T047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to load the file to be used in the process..
        /// </summary>
        internal static string T048 {
            get {
                return ResourceManager.GetString("T048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays the statistics of the file..
        /// </summary>
        internal static string T049 {
            get {
                return ResourceManager.GetString("T049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performs automatic balancing between active stations..
        /// </summary>
        internal static string T050 {
            get {
                return ResourceManager.GetString("T050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to load the file to carry out a verification with the process..
        /// </summary>
        internal static string T051 {
            get {
                return ResourceManager.GetString("T051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays the statistics of the file..
        /// </summary>
        internal static string T052 {
            get {
                return ResourceManager.GetString("T052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make a check if the current configuration works with the verified file..
        /// </summary>
        internal static string T053 {
            get {
                return ResourceManager.GetString("T053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send manual or automatic balancing to production..
        /// </summary>
        internal static string T054 {
            get {
                return ResourceManager.GetString("T054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string T055 {
            get {
                return ResourceManager.GetString("T055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        internal static string T056 {
            get {
                return ResourceManager.GetString("T056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference {0} was created..
        /// </summary>
        internal static string T057 {
            get {
                return ResourceManager.GetString("T057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference {0} already exists..
        /// </summary>
        internal static string T058 {
            get {
                return ResourceManager.GetString("T058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ID is empty..
        /// </summary>
        internal static string T059 {
            get {
                return ResourceManager.GetString("T059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference {0} has been updated..
        /// </summary>
        internal static string T060 {
            get {
                return ResourceManager.GetString("T060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this record?.
        /// </summary>
        internal static string T061 {
            get {
                return ResourceManager.GetString("T061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The reference {0} has been removed..
        /// </summary>
        internal static string T062 {
            get {
                return ResourceManager.GetString("T062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to select the type of action to be executed..
        /// </summary>
        internal static string T063 {
            get {
                return ResourceManager.GetString("T063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enter the name of the product ID..
        /// </summary>
        internal static string T064 {
            get {
                return ResourceManager.GetString("T064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to  select a product ID..
        /// </summary>
        internal static string T065 {
            get {
                return ResourceManager.GetString("T065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows updating the number of units that come in a product packaging..
        /// </summary>
        internal static string T066 {
            get {
                return ResourceManager.GetString("T066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to upload the product ID image..
        /// </summary>
        internal static string T067 {
            get {
                return ResourceManager.GetString("T067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to create a product ID..
        /// </summary>
        internal static string T068 {
            get {
                return ResourceManager.GetString("T068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to update a product ID..
        /// </summary>
        internal static string T069 {
            get {
                return ResourceManager.GetString("T069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to remove a product ID..
        /// </summary>
        internal static string T070 {
            get {
                return ResourceManager.GetString("T070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to select the scanner to be checked..
        /// </summary>
        internal static string T071 {
            get {
                return ResourceManager.GetString("T071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enable / disable communication with the scanner..
        /// </summary>
        internal static string T072 {
            get {
                return ResourceManager.GetString("T072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica la posicion en la que se tiene que encontrar el escanner y la lectura que realizo..
        /// </summary>
        internal static string T073 {
            get {
                return ResourceManager.GetString("T073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to update the data?.
        /// </summary>
        internal static string T074 {
            get {
                return ResourceManager.GetString("T074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fields have been updated..
        /// </summary>
        internal static string T075 {
            get {
                return ResourceManager.GetString("T075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to edit the time that the deactivated LEDs will last..
        /// </summary>
        internal static string T076 {
            get {
                return ResourceManager.GetString("T076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to edit the number of boxes per hour that pass..
        /// </summary>
        internal static string T077 {
            get {
                return ResourceManager.GetString("T077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows updating the data that was edited..
        /// </summary>
        internal static string T078 {
            get {
                return ResourceManager.GetString("T078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to add this record?.
        /// </summary>
        internal static string T079 {
            get {
                return ResourceManager.GetString("T079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to update this record?.
        /// </summary>
        internal static string T080 {
            get {
                return ResourceManager.GetString("T080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total of registers with vase: {0}.
        /// </summary>
        internal static string T081 {
            get {
                return ResourceManager.GetString("T081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string T082 {
            get {
                return ResourceManager.GetString("T082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string T083 {
            get {
                return ResourceManager.GetString("T083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        internal static string T084 {
            get {
                return ResourceManager.GetString("T084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string T085 {
            get {
                return ResourceManager.GetString("T085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to pause the system without losing the account..
        /// </summary>
        internal static string T086 {
            get {
                return ResourceManager.GetString("T086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to resume the current process?.
        /// </summary>
        internal static string T087 {
            get {
                return ResourceManager.GetString("T087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to pause the current process?.
        /// </summary>
        internal static string T088 {
            get {
                return ResourceManager.GetString("T088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conveyors and scanners will stop but you will not lose data..
        /// </summary>
        internal static string T089 {
            get {
                return ResourceManager.GetString("T089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a process running at this time. Do you want to cancel it?.
        /// </summary>
        internal static string T090 {
            get {
                return ResourceManager.GetString("T090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLCs are not connected.
        /// </summary>
        internal static string T091 {
            get {
                return ResourceManager.GetString("T091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string T092 {
            get {
                return ResourceManager.GetString("T092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        internal static string T093 {
            get {
                return ResourceManager.GetString("T093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A voltage drop was detected, the program will close and save the current status information..
        /// </summary>
        internal static string T094 {
            get {
                return ResourceManager.GetString("T094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you wish to recover the state you were in?.
        /// </summary>
        internal static string T095 {
            get {
                return ResourceManager.GetString("T095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to start?.
        /// </summary>
        internal static string T096 {
            get {
                return ResourceManager.GetString("T096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you finish this procedure, you must manually remove the boxes from the dispenser..
        /// </summary>
        internal static string T097 {
            get {
                return ResourceManager.GetString("T097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a stop.
        /// </summary>
        internal static string T098 {
            get {
                return ResourceManager.GetString("T098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start.
        /// </summary>
        internal static string T099 {
            get {
                return ResourceManager.GetString("T099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the reference {0} - {1}.
        /// </summary>
        internal static string T100 {
            get {
                return ResourceManager.GetString("T100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can prepare reference {0}.
        /// </summary>
        internal static string T101 {
            get {
                return ResourceManager.GetString("T101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 1.
        /// </summary>
        internal static string T102 {
            get {
                return ResourceManager.GetString("T102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T103 {
            get {
                return ResourceManager.GetString("T103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 2.
        /// </summary>
        internal static string T104 {
            get {
                return ResourceManager.GetString("T104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T105 {
            get {
                return ResourceManager.GetString("T105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 3.
        /// </summary>
        internal static string T106 {
            get {
                return ResourceManager.GetString("T106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T107 {
            get {
                return ResourceManager.GetString("T107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 4.
        /// </summary>
        internal static string T108 {
            get {
                return ResourceManager.GetString("T108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T109 {
            get {
                return ResourceManager.GetString("T109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 5.
        /// </summary>
        internal static string T110 {
            get {
                return ResourceManager.GetString("T110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T111 {
            get {
                return ResourceManager.GetString("T111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title 6.
        /// </summary>
        internal static string T112 {
            get {
                return ResourceManager.GetString("T112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T113 {
            get {
                return ResourceManager.GetString("T113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to EliteFlower.
        /// </summary>
        internal static string T114 {
            get {
                return ResourceManager.GetString("T114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string T115 {
            get {
                return ResourceManager.GetString("T115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string T116 {
            get {
                return ResourceManager.GetString("T116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get started.
        /// </summary>
        internal static string T117 {
            get {
                return ResourceManager.GetString("T117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string T118 {
            get {
                return ResourceManager.GetString("T118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main.
        /// </summary>
        internal static string T119 {
            get {
                return ResourceManager.GetString("T119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string T120 {
            get {
                return ResourceManager.GetString("T120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string T121 {
            get {
                return ResourceManager.GetString("T121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this record?.
        /// </summary>
        internal static string T122 {
            get {
                return ResourceManager.GetString("T122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The reference {0} has been removed..
        /// </summary>
        internal static string T123 {
            get {
                return ResourceManager.GetString("T123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to add this record?.
        /// </summary>
        internal static string T124 {
            get {
                return ResourceManager.GetString("T124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference {0} was created..
        /// </summary>
        internal static string T125 {
            get {
                return ResourceManager.GetString("T125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference {0} already exists..
        /// </summary>
        internal static string T126 {
            get {
                return ResourceManager.GetString("T126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ID is empty..
        /// </summary>
        internal static string T127 {
            get {
                return ResourceManager.GetString("T127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in the PLCs connection.
        /// </summary>
        internal static string T128 {
            get {
                return ResourceManager.GetString("T128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to select between adding or removing packaging from the products..
        /// </summary>
        internal static string T129 {
            get {
                return ResourceManager.GetString("T129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to view the image of the Addon to be removed..
        /// </summary>
        internal static string T130 {
            get {
                return ResourceManager.GetString("T130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to visualize the image of the Addon to create..
        /// </summary>
        internal static string T131 {
            get {
                return ResourceManager.GetString("T131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to enter the name by which the Addon is represented..
        /// </summary>
        internal static string T132 {
            get {
                return ResourceManager.GetString("T132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to list the Addons that can be removed..
        /// </summary>
        internal static string T133 {
            get {
                return ResourceManager.GetString("T133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enter the image of the Addon to create..
        /// </summary>
        internal static string T134 {
            get {
                return ResourceManager.GetString("T134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to delete the selected Addon..
        /// </summary>
        internal static string T135 {
            get {
                return ResourceManager.GetString("T135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows adding an Addon according to the image and name entered..
        /// </summary>
        internal static string T136 {
            get {
                return ResourceManager.GetString("T136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It cannot be deleted, there are products that use this value:.
        /// </summary>
        internal static string T137 {
            get {
                return ResourceManager.GetString("T137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vase: {0}.
        /// </summary>
        internal static string T138 {
            get {
                return ResourceManager.GetString("T138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to select between adding or removing packaging from the products..
        /// </summary>
        internal static string T139 {
            get {
                return ResourceManager.GetString("T139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to list the packaging of the products..
        /// </summary>
        internal static string T140 {
            get {
                return ResourceManager.GetString("T140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to create a packaging of the products..
        /// </summary>
        internal static string T141 {
            get {
                return ResourceManager.GetString("T141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It allows to eliminate a packaging of the products as long as it is not linked to products..
        /// </summary>
        internal static string T142 {
            get {
                return ResourceManager.GetString("T142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allows you to enter the units by which the product is packed..
        /// </summary>
        internal static string T143 {
            get {
                return ResourceManager.GetString("T143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add some packaging size of the products..
        /// </summary>
        internal static string T144 {
            get {
                return ResourceManager.GetString("T144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balancing data.
        /// </summary>
        internal static string T145 {
            get {
                return ResourceManager.GetString("T145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploading balanced data.
        /// </summary>
        internal static string T146 {
            get {
                return ResourceManager.GetString("T146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic balancing performed.
        /// </summary>
        internal static string T147 {
            get {
                return ResourceManager.GetString("T147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling balanced data.
        /// </summary>
        internal static string T148 {
            get {
                return ResourceManager.GetString("T148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual balancing performed.
        /// </summary>
        internal static string T149 {
            get {
                return ResourceManager.GetString("T149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can lose all the history you have up to now. Do you want to add a new file?.
        /// </summary>
        internal static string T150 {
            get {
                return ResourceManager.GetString("T150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading new data.
        /// </summary>
        internal static string T151 {
            get {
                return ResourceManager.GetString("T151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data uploaded successfully..
        /// </summary>
        internal static string T152 {
            get {
                return ResourceManager.GetString("T152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to update the file with new information?.
        /// </summary>
        internal static string T153 {
            get {
                return ResourceManager.GetString("T153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating new data.
        /// </summary>
        internal static string T154 {
            get {
                return ResourceManager.GetString("T154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data updated successfully..
        /// </summary>
        internal static string T155 {
            get {
                return ResourceManager.GetString("T155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can lose part of the history you have up to now. Do you want to get backup?.
        /// </summary>
        internal static string T156 {
            get {
                return ResourceManager.GetString("T156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to perform manual balancing?.
        /// </summary>
        internal static string T157 {
            get {
                return ResourceManager.GetString("T157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual balance data.
        /// </summary>
        internal static string T158 {
            get {
                return ResourceManager.GetString("T158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual balancing performed.
        /// </summary>
        internal static string T159 {
            get {
                return ResourceManager.GetString("T159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The products were modified in the stations and manual balancing was not performed. Do you want to do it?.
        /// </summary>
        internal static string T160 {
            get {
                return ResourceManager.GetString("T160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceling manual balanced data.
        /// </summary>
        internal static string T161 {
            get {
                return ResourceManager.GetString("T161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual balancing canceled.
        /// </summary>
        internal static string T162 {
            get {
                return ResourceManager.GetString("T162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of elevators up {0}..
        /// </summary>
        internal static string T163 {
            get {
                return ResourceManager.GetString("T163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next elevator: {0} in elevator {1}..
        /// </summary>
        internal static string T164 {
            get {
                return ResourceManager.GetString("T164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of empty lungs {0}..
        /// </summary>
        internal static string T165 {
            get {
                return ResourceManager.GetString("T165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next box: {0} in elevator {1}..
        /// </summary>
        internal static string T166 {
            get {
                return ResourceManager.GetString("T166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file has not yet been balanced..
        /// </summary>
        internal static string T167 {
            get {
                return ResourceManager.GetString("T167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The balancing has not been selected well..
        /// </summary>
        internal static string T168 {
            get {
                return ResourceManager.GetString("T168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las cajas que se deben quitar son:.
        /// </summary>
        internal static string T169 {
            get {
                return ResourceManager.GetString("T169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevator {0}.
        /// </summary>
        internal static string T170 {
            get {
                return ResourceManager.GetString("T170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System shutdown was completed.
        /// </summary>
        internal static string T171 {
            get {
                return ResourceManager.GetString("T171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergency stop activated.
        /// </summary>
        internal static string T172 {
            get {
                return ResourceManager.GetString("T172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} orders have been processed..
        /// </summary>
        internal static string T173 {
            get {
                return ResourceManager.GetString("T173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amount to fill {0}.
        /// </summary>
        internal static string T174 {
            get {
                return ResourceManager.GetString("T174", resourceCulture);
            }
        }
    }
}
