//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteFlower.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUI_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUI_en_US() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EliteFlower.Properties.ResourceUI-en-US", typeof(ResourceUI_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dwewe.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Barcode Scanner.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable stations.
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Station {0}.
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vase {0}.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conveyors.
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conveyor {0}.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check.
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load image.
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package.
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect.
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disconnect.
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Station {0} - Band {1}.
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer OFF [s].
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conveyor.
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conveyor speed {0} [boxes/h].
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lights / Conveyours.
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motors.
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New data.
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update data.
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore Backup.
        /// </summary>
        internal static string T036 {
            get {
                return ResourceManager.GetString("T036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boxes / hour.
        /// </summary>
        internal static string T037 {
            get {
                return ResourceManager.GetString("T037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write.
        /// </summary>
        internal static string T038 {
            get {
                return ResourceManager.GetString("T038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        internal static string T039 {
            get {
                return ResourceManager.GetString("T039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zone {0}.
        /// </summary>
        internal static string T040 {
            get {
                return ResourceManager.GetString("T040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevator.
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorter.
        /// </summary>
        internal static string T042 {
            get {
                return ResourceManager.GetString("T042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pusher.
        /// </summary>
        internal static string T043 {
            get {
                return ResourceManager.GetString("T043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pusher/Sorter.
        /// </summary>
        internal static string T044 {
            get {
                return ResourceManager.GetString("T044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feeder.
        /// </summary>
        internal static string T045 {
            get {
                return ResourceManager.GetString("T045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stations.
        /// </summary>
        internal static string T046 {
            get {
                return ResourceManager.GetString("T046", resourceCulture);
            }
        }
    }
}
