//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteFlower.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMsg_es_CO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMsg_es_CO() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EliteFlower.Properties.ResourceMsg-es-CO", typeof(ResourceMsg_es_CO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Necesitas ayuda?.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que quiere salir?.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Inicar el proceso?.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado ninguna estación.
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan los siguientes escáner:.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor conectar los escáner que hacen falta..
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El balanceo y las estaciones seleccionadas no coinciden..
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea parar el proceso actual?.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perderá la cuenta y los datos que lleva hasta el momento..
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han seleccionado algunos parámetros..
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo: {0}.
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de registros: {0}.
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilite mas estaciones, el archivo cuenta con {0} productos diferentes..
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiere agregar los siguientes productos a la estacion {0}?.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto {0}: {1},.
        /// </summary>
        internal static string T015 {
            get {
                return ResourceManager.GetString("T015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendación:.
        /// </summary>
        internal static string T016 {
            get {
                return ResourceManager.GetString("T016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacion {0} con productos.
        /// </summary>
        internal static string T017 {
            get {
                return ResourceManager.GetString("T017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiere realizar el cambio?.
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto: {0} - Cantidad: {1}.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de productos son{0}.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sugerencia: Use una estacion.
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sugerencia: Use 2 estaciones.
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sugerencia: Use 3 estaciones.
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota: La maquina no puede procesar mas de 9 productos..
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes IDs no se encuentran en la base de datos..
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese la información necesaria para continuar..
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizo una modificación manual, puede que los datos cambiados no estén balanceados.
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea cargar los cambios generados?.
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quedaron productos sin asignar que se encuentran en el archivo:.
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID: {0} - Cantidad: {1}.
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede verificar con una o menos estaciones activas..
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verificar que ambos archivos se seleccionaron con la misma cantidad de estaciones habilitadas..
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se puede usar la configuración actual..
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede usar la configuración actual..
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer el cambio en.
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estación {0} y.
        /// </summary>
        internal static string T036 {
            get {
                return ResourceManager.GetString("T036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estación {0}..
        /// </summary>
        internal static string T037 {
            get {
                return ResourceManager.GetString("T037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacion {0} con: {1}, {2} y {3}..
        /// </summary>
        internal static string T038 {
            get {
                return ResourceManager.GetString("T038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No coinciden las estaciones seleccionadas con los balanceos actuales..
        /// </summary>
        internal static string T039 {
            get {
                return ResourceManager.GetString("T039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo del archivo actual:.
        /// </summary>
        internal static string T040 {
            get {
                return ResourceManager.GetString("T040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo del próximo archivo:.
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estaciones habilitadas:.
        /// </summary>
        internal static string T042 {
            get {
                return ResourceManager.GetString("T042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar estaciones correctas y/o recargar el archivo que sigue nuevamente..
        /// </summary>
        internal static string T043 {
            get {
                return ResourceManager.GetString("T043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estación {0},.
        /// </summary>
        internal static string T044 {
            get {
                return ResourceManager.GetString("T044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite activar/desactivar las estaciones..
        /// </summary>
        internal static string T045 {
            get {
                return ResourceManager.GetString("T045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar manualmente los productos que van a ir por estación..
        /// </summary>
        internal static string T046 {
            get {
                return ResourceManager.GetString("T046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite activar/desactivar las bandas..
        /// </summary>
        internal static string T047 {
            get {
                return ResourceManager.GetString("T047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite cargar el archivo que se utilizar en el proceso..
        /// </summary>
        internal static string T048 {
            get {
                return ResourceManager.GetString("T048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra las estadísticas del archivo..
        /// </summary>
        internal static string T049 {
            get {
                return ResourceManager.GetString("T049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza el balanceo automático entre las estaciones activas..
        /// </summary>
        internal static string T050 {
            get {
                return ResourceManager.GetString("T050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite cargar el archivo para realizar una verificación con el del proceso..
        /// </summary>
        internal static string T051 {
            get {
                return ResourceManager.GetString("T051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra las estadísticas del archivo..
        /// </summary>
        internal static string T052 {
            get {
                return ResourceManager.GetString("T052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza un chequeo si la configuración actual sirve con el archivo verificado..
        /// </summary>
        internal static string T053 {
            get {
                return ResourceManager.GetString("T053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviá el balanceo manual o automático a producción..
        /// </summary>
        internal static string T054 {
            get {
                return ResourceManager.GetString("T054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string T055 {
            get {
                return ResourceManager.GetString("T055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parar.
        /// </summary>
        internal static string T056 {
            get {
                return ResourceManager.GetString("T056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia {0} fue creada..
        /// </summary>
        internal static string T057 {
            get {
                return ResourceManager.GetString("T057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia {0} ya existe..
        /// </summary>
        internal static string T058 {
            get {
                return ResourceManager.GetString("T058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID esta vació..
        /// </summary>
        internal static string T059 {
            get {
                return ResourceManager.GetString("T059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia {0} se ha actualizado..
        /// </summary>
        internal static string T060 {
            get {
                return ResourceManager.GetString("T060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quiere eliminar este registro?.
        /// </summary>
        internal static string T061 {
            get {
                return ResourceManager.GetString("T061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia {0} se ha eliminado..
        /// </summary>
        internal static string T062 {
            get {
                return ResourceManager.GetString("T062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar el tipo de acción que se va ejecutar..
        /// </summary>
        internal static string T063 {
            get {
                return ResourceManager.GetString("T063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite ingresar el nombre del ID del producto..
        /// </summary>
        internal static string T064 {
            get {
                return ResourceManager.GetString("T064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar un ID de los productos..
        /// </summary>
        internal static string T065 {
            get {
                return ResourceManager.GetString("T065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite actualizar la cantidad de unidades que vienen en un empaque del producto..
        /// </summary>
        internal static string T066 {
            get {
                return ResourceManager.GetString("T066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite cargar la imagen del ID del producto..
        /// </summary>
        internal static string T067 {
            get {
                return ResourceManager.GetString("T067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite crear un ID de un producto..
        /// </summary>
        internal static string T068 {
            get {
                return ResourceManager.GetString("T068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite actualizar un ID de un producto..
        /// </summary>
        internal static string T069 {
            get {
                return ResourceManager.GetString("T069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite borrar un ID de un producto..
        /// </summary>
        internal static string T070 {
            get {
                return ResourceManager.GetString("T070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar el escáner que se va a comprobar..
        /// </summary>
        internal static string T071 {
            get {
                return ResourceManager.GetString("T071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite activar/desactivar la comunicación con el escáner..
        /// </summary>
        internal static string T072 {
            get {
                return ResourceManager.GetString("T072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica la posición en la que se tiene que encontrar el escáner y la lectura que realizo..
        /// </summary>
        internal static string T073 {
            get {
                return ResourceManager.GetString("T073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de actualizar los datos?.
        /// </summary>
        internal static string T074 {
            get {
                return ResourceManager.GetString("T074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos se han actualizado..
        /// </summary>
        internal static string T075 {
            get {
                return ResourceManager.GetString("T075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite editar el tiempo que van a durar los leds desactivados..
        /// </summary>
        internal static string T076 {
            get {
                return ResourceManager.GetString("T076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite editar la cantidad de cajas por hora que pasan..
        /// </summary>
        internal static string T077 {
            get {
                return ResourceManager.GetString("T077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite actualizar los datos que se editaron..
        /// </summary>
        internal static string T078 {
            get {
                return ResourceManager.GetString("T078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea agregar el ID del producto?.
        /// </summary>
        internal static string T079 {
            get {
                return ResourceManager.GetString("T079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea editar el ID del producto?.
        /// </summary>
        internal static string T080 {
            get {
                return ResourceManager.GetString("T080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de registros con vase: {0}.
        /// </summary>
        internal static string T081 {
            get {
                return ResourceManager.GetString("T081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        internal static string T082 {
            get {
                return ResourceManager.GetString("T082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string T083 {
            get {
                return ResourceManager.GetString("T083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        internal static string T084 {
            get {
                return ResourceManager.GetString("T084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string T085 {
            get {
                return ResourceManager.GetString("T085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite pausar el sistema sin que se pierda la cuenta..
        /// </summary>
        internal static string T086 {
            get {
                return ResourceManager.GetString("T086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea reanudar el proceso actual?.
        /// </summary>
        internal static string T087 {
            get {
                return ResourceManager.GetString("T087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea pausar el proceso actual?.
        /// </summary>
        internal static string T088 {
            get {
                return ResourceManager.GetString("T088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detendran las bandas y los escaners pero no perdera los datos..
        /// </summary>
        internal static string T089 {
            get {
                return ResourceManager.GetString("T089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un proceso ejecutandose en este momento. Lo quiere cancelar?.
        /// </summary>
        internal static string T090 {
            get {
                return ResourceManager.GetString("T090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLCs no estan conectados.
        /// </summary>
        internal static string T091 {
            get {
                return ResourceManager.GetString("T091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausar.
        /// </summary>
        internal static string T092 {
            get {
                return ResourceManager.GetString("T092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausado.
        /// </summary>
        internal static string T093 {
            get {
                return ResourceManager.GetString("T093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detecto una caida de voltaje, el programa se cerrara y guardara la informacion de como se encuentra en el momento.
        /// </summary>
        internal static string T094 {
            get {
                return ResourceManager.GetString("T094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea recuperar el estado en el que se encontraba?.
        /// </summary>
        internal static string T095 {
            get {
                return ResourceManager.GetString("T095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de iniciar?.
        /// </summary>
        internal static string T096 {
            get {
                return ResourceManager.GetString("T096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si para este procedimiento debera sacar manualmente las cajas del dispensador.
        /// </summary>
        internal static string T097 {
            get {
                return ResourceManager.GetString("T097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parar.
        /// </summary>
        internal static string T098 {
            get {
                return ResourceManager.GetString("T098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string T099 {
            get {
                return ResourceManager.GetString("T099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la refencia {0} - {1}.
        /// </summary>
        internal static string T100 {
            get {
                return ResourceManager.GetString("T100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede ir preparando la referencia {0}.
        /// </summary>
        internal static string T101 {
            get {
                return ResourceManager.GetString("T101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 1.
        /// </summary>
        internal static string T102 {
            get {
                return ResourceManager.GetString("T102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T103 {
            get {
                return ResourceManager.GetString("T103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 2.
        /// </summary>
        internal static string T104 {
            get {
                return ResourceManager.GetString("T104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T105 {
            get {
                return ResourceManager.GetString("T105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 3.
        /// </summary>
        internal static string T106 {
            get {
                return ResourceManager.GetString("T106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T107 {
            get {
                return ResourceManager.GetString("T107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 4.
        /// </summary>
        internal static string T108 {
            get {
                return ResourceManager.GetString("T108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T109 {
            get {
                return ResourceManager.GetString("T109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 5.
        /// </summary>
        internal static string T110 {
            get {
                return ResourceManager.GetString("T110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T111 {
            get {
                return ResourceManager.GetString("T111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo 6.
        /// </summary>
        internal static string T112 {
            get {
                return ResourceManager.GetString("T112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lectus urna, tristique sed dui dictum, congue lobortis velit. Duis blandit..
        /// </summary>
        internal static string T113 {
            get {
                return ResourceManager.GetString("T113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a EliteFlower.
        /// </summary>
        internal static string T114 {
            get {
                return ResourceManager.GetString("T114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        internal static string T115 {
            get {
                return ResourceManager.GetString("T115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string T116 {
            get {
                return ResourceManager.GetString("T116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string T117 {
            get {
                return ResourceManager.GetString("T117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string T118 {
            get {
                return ResourceManager.GetString("T118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string T119 {
            get {
                return ResourceManager.GetString("T119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        internal static string T120 {
            get {
                return ResourceManager.GetString("T120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string T121 {
            get {
                return ResourceManager.GetString("T121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea eliminar el registro?.
        /// </summary>
        internal static string T122 {
            get {
                return ResourceManager.GetString("T122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia {0} fue eliminada..
        /// </summary>
        internal static string T123 {
            get {
                return ResourceManager.GetString("T123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea agregar el registro?.
        /// </summary>
        internal static string T124 {
            get {
                return ResourceManager.GetString("T124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia {0} fue creada..
        /// </summary>
        internal static string T125 {
            get {
                return ResourceManager.GetString("T125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia {0} ya existe..
        /// </summary>
        internal static string T126 {
            get {
                return ResourceManager.GetString("T126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo ID esta vacio..
        /// </summary>
        internal static string T127 {
            get {
                return ResourceManager.GetString("T127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexion de los PLCs.
        /// </summary>
        internal static string T128 {
            get {
                return ResourceManager.GetString("T128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar entre agregar o eliminar un empaque de los productos..
        /// </summary>
        internal static string T129 {
            get {
                return ResourceManager.GetString("T129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite visualizar la imagen del Addon a eliminar..
        /// </summary>
        internal static string T130 {
            get {
                return ResourceManager.GetString("T130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite visualizar la imagen del Addon a crear..
        /// </summary>
        internal static string T131 {
            get {
                return ResourceManager.GetString("T131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite ingresar el nombre alfanumero por el cual se representa el Addon..
        /// </summary>
        internal static string T132 {
            get {
                return ResourceManager.GetString("T132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite listar los Addons que pueden ser eliminados..
        /// </summary>
        internal static string T133 {
            get {
                return ResourceManager.GetString("T133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite ingresar la imagen del Addon a crear..
        /// </summary>
        internal static string T134 {
            get {
                return ResourceManager.GetString("T134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite eliminar el Addon seleccionado..
        /// </summary>
        internal static string T135 {
            get {
                return ResourceManager.GetString("T135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite agregar un Addon segun la imagen y nombre ingresado..
        /// </summary>
        internal static string T136 {
            get {
                return ResourceManager.GetString("T136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar, existen productos que usan este valor:\n\n.
        /// </summary>
        internal static string T137 {
            get {
                return ResourceManager.GetString("T137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipiente: {0}\n.
        /// </summary>
        internal static string T138 {
            get {
                return ResourceManager.GetString("T138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite seleccionar entre agregar o eliminar un empaque de los productos..
        /// </summary>
        internal static string T139 {
            get {
                return ResourceManager.GetString("T139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite listar los empaques de los productos..
        /// </summary>
        internal static string T140 {
            get {
                return ResourceManager.GetString("T140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite crear un empaque de los productos..
        /// </summary>
        internal static string T141 {
            get {
                return ResourceManager.GetString("T141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite eliminar un empaque de los productos siempre y cuando no este vinculado con productos..
        /// </summary>
        internal static string T142 {
            get {
                return ResourceManager.GetString("T142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite ingresar las unidades por la cual se empaca el producto..
        /// </summary>
        internal static string T143 {
            get {
                return ResourceManager.GetString("T143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrege algun tamaño de empaque de los productos..
        /// </summary>
        internal static string T144 {
            get {
                return ResourceManager.GetString("T144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceando los datos.
        /// </summary>
        internal static string T145 {
            get {
                return ResourceManager.GetString("T145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subiendo datos balanceados.
        /// </summary>
        internal static string T146 {
            get {
                return ResourceManager.GetString("T146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo automatico efectuado.
        /// </summary>
        internal static string T147 {
            get {
                return ResourceManager.GetString("T147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelando datos balanceados.
        /// </summary>
        internal static string T148 {
            get {
                return ResourceManager.GetString("T148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo manual efectuado.
        /// </summary>
        internal static string T149 {
            get {
                return ResourceManager.GetString("T149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede perder todo el historico que lleva hasta el momento. ¿Desea agregar un nuevo archivo?.
        /// </summary>
        internal static string T150 {
            get {
                return ResourceManager.GetString("T150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando datos nuevos.
        /// </summary>
        internal static string T151 {
            get {
                return ResourceManager.GetString("T151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos cargados satisfactoriamente..
        /// </summary>
        internal static string T152 {
            get {
                return ResourceManager.GetString("T152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿desea actualizar el archivo con nueva informacion?.
        /// </summary>
        internal static string T153 {
            get {
                return ResourceManager.GetString("T153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando datos nuevos.
        /// </summary>
        internal static string T154 {
            get {
                return ResourceManager.GetString("T154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos actualizados satisfactoriamente..
        /// </summary>
        internal static string T155 {
            get {
                return ResourceManager.GetString("T155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede perder parte del historico que lleva hasta el momento. ¿Desea obtener copia de seguridad?.
        /// </summary>
        internal static string T156 {
            get {
                return ResourceManager.GetString("T156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea realizar el balanceo manual?.
        /// </summary>
        internal static string T157 {
            get {
                return ResourceManager.GetString("T157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo manual.
        /// </summary>
        internal static string T158 {
            get {
                return ResourceManager.GetString("T158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo manual efectuado.
        /// </summary>
        internal static string T159 {
            get {
                return ResourceManager.GetString("T159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se modificaron los productos en las estaciones y no se realizó el balanceo manual. ¿Quieres hacerlo?.
        /// </summary>
        internal static string T160 {
            get {
                return ResourceManager.GetString("T160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelando balanceo manual.
        /// </summary>
        internal static string T161 {
            get {
                return ResourceManager.GetString("T161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balanceo manual cancelado.
        /// </summary>
        internal static string T162 {
            get {
                return ResourceManager.GetString("T162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de elevadores arriba {0}..
        /// </summary>
        internal static string T163 {
            get {
                return ResourceManager.GetString("T163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proximo elevador: {0} en elevador {1}..
        /// </summary>
        internal static string T164 {
            get {
                return ResourceManager.GetString("T164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de pulmones vacios {0}..
        /// </summary>
        internal static string T165 {
            get {
                return ResourceManager.GetString("T165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proxima caja: {0} en elevador {1}..
        /// </summary>
        internal static string T166 {
            get {
                return ResourceManager.GetString("T166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todavia no se ha balanceado el archivo..
        /// </summary>
        internal static string T167 {
            get {
                return ResourceManager.GetString("T167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado bien el balanceo..
        /// </summary>
        internal static string T168 {
            get {
                return ResourceManager.GetString("T168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las cajas que se deben quitar son:.
        /// </summary>
        internal static string T169 {
            get {
                return ResourceManager.GetString("T169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevador {0}.
        /// </summary>
        internal static string T170 {
            get {
                return ResourceManager.GetString("T170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se finalizo parada del sistema.
        /// </summary>
        internal static string T171 {
            get {
                return ResourceManager.GetString("T171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activo paro de emergencia.
        /// </summary>
        internal static string T172 {
            get {
                return ResourceManager.GetString("T172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han procesado {0} ordenes..
        /// </summary>
        internal static string T173 {
            get {
                return ResourceManager.GetString("T173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad a llenar {0}.
        /// </summary>
        internal static string T174 {
            get {
                return ResourceManager.GetString("T174", resourceCulture);
            }
        }
    }
}
